#!/usr/bin/env bash
# sync-memory.sh — Sync vault memory to agent-specific files in a project repo.
#
# Usage:
#   sync-memory.sh <repo-path>              Sync one project by repo path
#   sync-memory.sh --all                    Sync all registered projects
#   sync-memory.sh <repo-path> --dry-run    Preview without writing files
#
# The script auto-detects the project name from the repo folder name, finds the
# matching vault project (including nested modules), and generates agent files
# with the right context layering:
#
#   Top-level project → AGENTS.md + project OVERVIEW
#   Module project    → AGENTS.md + module OVERVIEW + parent OVERVIEW
#
# It also installs per-agent SessionStart hooks and injects a fallback
# MANDATORY SESSION START CONTEXT block at the top of each generated file.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PATHS_FILE="$REPO_DIR/.project-paths"

# Resolve the actual CORA vault, which may live outside this repo.
normalize_vault_path() {
    local raw="$1"
    raw="${raw//\\ / }"
    raw="${raw//\\~/~}"
    raw="${raw//\\:/:}"
    printf '%s' "$raw"
}

resolve_vault() {
    local vault="${AGENT_MEMORY_VAULT:-}"
    vault="$(normalize_vault_path "$vault")"

    if [[ -z "$vault" || ! -f "$vault/AGENTS.md" ]]; then
        if [[ -f "${HOME}/obsidian-memory-vault/AGENTS.md" ]]; then
            vault="${HOME}/obsidian-memory-vault"
        elif [[ -f "${HOME}/Library/Mobile Documents/iCloud~md~obsidian/Documents/rm-memory-vault/AGENTS.md" ]]; then
            vault="${HOME}/Library/Mobile Documents/iCloud~md~obsidian/Documents/rm-memory-vault"
        fi
    fi

    if [[ -z "$vault" || ! -f "$vault/AGENTS.md" ]]; then
        err "Could not resolve CORA vault. Set \$AGENT_MEMORY_VAULT or create ~/obsidian-memory-vault."
        exit 1
    fi

    echo "$vault"
}

VAULT_DIR="$(resolve_vault)"
AGENTS_FILE="$VAULT_DIR/AGENTS.md"
SESSION_START_SCRIPT="$VAULT_DIR/scripts/cora-session-start.sh"

DRY_RUN=false

# ── Helpers ──────────────────────────────────────────────────────────────────

log()  { echo "  $*"; }
ok()   { echo "  ✓ $*"; }
warn() { echo "  ⚠ $*" >&2; }
err()  { echo "  ✗ $*" >&2; }

write_file() {
    local path="$1"
    local content="$2"
    if $DRY_RUN; then
        echo "  [dry-run] would write: $path"
    else
        mkdir -p "$(dirname "$path")"
        echo "$content" > "$path"
        ok "$path"
    fi
}

write_executable() {
    local path="$1"
    local content="$2"
    write_file "$path" "$content"
    if ! $DRY_RUN; then
        chmod +x "$path"
    fi
}

# Find vault project dir for a given project name (searches all nesting levels)
find_vault_project() {
    local name="$1"
    find "$VAULT_DIR/projects" -type d -name "$name" -maxdepth 4 2>/dev/null | head -1
}

# Compute the session-start recap for a project.
compute_session_context() {
    local project_name="$1"
    if [[ -x "$SESSION_START_SCRIPT" ]]; then
        "$SESSION_START_SCRIPT" "$project_name" 2>/dev/null || true
    else
        echo "MANDATORY SESSION START CONTEXT"
        echo "Project: $project_name"
        echo "Last session: unknown"
        echo ""
        echo "Activity since last session:"
        echo "- (session-start helper not available)"
    fi
}

# Build the agent file content for a given repo path
build_agent_content() {
    local project_name="$1"
    local vault_project_dir="$2"  # may be empty if no vault project found
    local session_context="$3"
    local timestamp
    timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

    local content
    content="$(cat << EOF
# MANDATORY SESSION START CONTEXT — surfaced by per-agent SessionStart hook
# If you are reading this file directly, you MUST surface this section to the
# user before answering, unless they opened with a quick one-off question or a
# non-project context. See AGENTS.md Session Start Protocol.
#
$session_context

# Agent Memory
# Auto-generated by sync-memory.sh — do not edit manually.
# Vault: $VAULT_DIR
# Synced: $timestamp

$(cat "$AGENTS_FILE")
EOF
)"

    if [[ -n "$vault_project_dir" ]]; then
        local parent_dir
        parent_dir="$(dirname "$vault_project_dir")"
        local is_module=false

        # If the parent dir contains an OVERVIEW.md, this is a module
        if [[ "$parent_dir" != "$VAULT_DIR/projects" && -f "$parent_dir/OVERVIEW.md" ]]; then
            is_module=true
        fi

        # Append module OVERVIEW
        if [[ -f "$vault_project_dir/OVERVIEW.md" ]]; then
            content+="

---
# Module Context: $project_name

$(cat "$vault_project_dir/OVERVIEW.md")"
        fi

        # Append parent OVERVIEW if this is a module
        if $is_module && [[ -f "$parent_dir/OVERVIEW.md" ]]; then
            local parent_name
            parent_name="$(basename "$parent_dir")"
            content+="

---
# System Context: $parent_name (parent project)

$(cat "$parent_dir/OVERVIEW.md")"
        fi
    fi

    echo "$content"
}

# ── Per-agent hooks ──────────────────────────────────────────────────────────

# Write a SessionStart hook wrapper for one agent.
# Arguments: repo_path, hook_dir, json_body (the agent-specific JSON field block)
write_agent_wrapper() {
    local repo_path="$1"
    local hook_dir="$2"
    local json_body="$3"
    local path="$repo_path/$hook_dir/cora-session-start.sh"

    local content
    content="$(cat << EOF
#!/usr/bin/env bash
# CORA SessionStart hook wrapper — auto-generated by sync-memory.sh
# Calls the vault helper and returns JSON for this agent.
set -euo pipefail
SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
PROJECT_NAME="$project_name"
SESSION_START_SCRIPT="$SESSION_START_SCRIPT"

RECAP="\$("\$SESSION_START_SCRIPT" "\$PROJECT_NAME" 2>"\$SCRIPT_DIR/cora-session-start.log")"

# Escape multi-line text for JSON
RECAP_JSON="\$(printf '%s' "\$RECAP" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()), end="")')"

cat << JSON
{
  $json_body
}
JSON
EOF
)"
    if $DRY_RUN; then
        echo "  [dry-run] would write: $path"
    else
        mkdir -p "$repo_path/$hook_dir"
        echo "$content" > "$path"
        chmod +x "$path"
        ok "$path"
    fi
}

write_hook_wrappers() {
    local repo_path="$1"
    local project_name="$2"

    # shellcheck disable=SC2016  # $RECAP_JSON is a template placeholder, not a shell variable
    # Claude Code expects hookSpecificOutput.hookEventName + additionalContext
    write_agent_wrapper "$repo_path" ".claude/hooks" '
  "hookSpecificOutput": {
    "hookEventName": "SessionStart",
    "additionalContext": $RECAP_JSON
  }'

    # Codex expects hookSpecificOutput.hookEventName + additionalContext
    write_agent_wrapper "$repo_path" ".codex/hooks" '
  "hookSpecificOutput": {
    "hookEventName": "SessionStart",
    "additionalContext": $RECAP_JSON
  }'

    # Gemini expects hookSpecificOutput.additionalContext
    write_agent_wrapper "$repo_path" ".gemini/hooks" '
  "hookSpecificOutput": {
    "additionalContext": $RECAP_JSON
  }'

    # GitHub Copilot expects top-level additionalContext
    write_agent_wrapper "$repo_path" ".github/hooks" '
  "additionalContext": $RECAP_JSON'
}

write_hook_configs() {
    local repo_path="$1"

    # Claude Code — .claude/settings.json
    local claude_config
    claude_config='{
  "hooks": {
    "SessionStart": [
      {
        "matcher": "startup|resume|clear|compact",
        "type": "command",
        "command": ".claude/hooks/cora-session-start.sh"
      }
    ]
  }
}'
    if [[ -f "$repo_path/.claude/settings.json" ]]; then
        if grep -qF "cora-session-start.sh" "$repo_path/.claude/settings.json" 2>/dev/null; then
            log ".claude/settings.json already contains CORA SessionStart hook"
        else
            warn ".claude/settings.json already exists — leaving untouched."
            warn "Add this SessionStart hook manually if you want CORA enforcement:"
            echo "$claude_config"
        fi
    else
        write_file "$repo_path/.claude/settings.json" "$claude_config"
    fi

    # Codex — .codex/hooks.json
    local codex_config
    codex_config='{
  "hooks": {
    "SessionStart": [
      {
        "matcher": "startup|resume|clear|compact",
        "type": "command",
        "command": ".codex/hooks/cora-session-start.sh"
      }
    ]
  }
}'
    if [[ -f "$repo_path/.codex/hooks.json" ]]; then
        if grep -qF "cora-session-start.sh" "$repo_path/.codex/hooks.json" 2>/dev/null; then
            log ".codex/hooks.json already contains CORA SessionStart hook"
        else
            warn ".codex/hooks.json already exists — leaving untouched."
            warn "Add this SessionStart hook manually if you want CORA enforcement:"
            echo "$codex_config"
        fi
    else
        write_file "$repo_path/.codex/hooks.json" "$codex_config"
    fi

    # Gemini — .gemini/hooks.json
    local gemini_config
    gemini_config='{
  "hooks": {
    "SessionStart": [
      {
        "matcher": "startup|resume|clear|compact",
        "type": "command",
        "command": ".gemini/hooks/cora-session-start.sh"
      }
    ]
  }
}'
    if [[ -f "$repo_path/.gemini/hooks.json" ]]; then
        if grep -qF "cora-session-start.sh" "$repo_path/.gemini/hooks.json" 2>/dev/null; then
            log ".gemini/hooks.json already contains CORA SessionStart hook"
        else
            warn ".gemini/hooks.json already exists — leaving untouched."
            warn "Add this SessionStart hook manually if you want CORA enforcement:"
            echo "$gemini_config"
        fi
    else
        write_file "$repo_path/.gemini/hooks.json" "$gemini_config"
    fi

    # GitHub Copilot — .github/hooks/cora-session-start.json
    # Leave any existing .github/hooks/hooks.json untouched.
    local copilot_config
    copilot_config='{
  "version": 1,
  "hooks": {
    "sessionStart": [
      {
        "type": "command",
        "bash": ".github/hooks/cora-session-start.sh"
      }
    ]
  }
}'
    if [[ -f "$repo_path/.github/hooks/cora-session-start.json" ]]; then
        log ".github/hooks/cora-session-start.json already exists"
    else
        write_file "$repo_path/.github/hooks/cora-session-start.json" "$copilot_config"
    fi
}

# ── .gitignore ────────────────────────────────────────────────────────────────

update_gitignore() {
    local repo_path="$1"
    local gitignore_file="$repo_path/.gitignore"
    local marker="# Agent memory files — auto-generated"

    if [[ -f "$gitignore_file" ]] && grep -qF "$marker" "$gitignore_file"; then
        log ".gitignore already covers agent files"
        return 0
    fi

    local entries
    entries=$(cat << EOF

$marker
.claude/
.gemini/
.codex/
.github/copilot-instructions.md
.github/hooks/cora-session-start*
EOF
)
    if $DRY_RUN; then
        echo "  [dry-run] would append agent entries to $gitignore_file"
        return 0
    fi

    echo "$entries" >> "$gitignore_file"
    ok "Updated $gitignore_file with agent entries"
}

# Sync one project repo
sync_project() {
    local repo_path="$1"

    if [[ ! -d "$repo_path" ]]; then
        err "Path does not exist: $repo_path"
        return 1
    fi

    local project_name
    project_name="$(basename "$repo_path")"
    echo ""
    echo "→ $project_name  ($repo_path)"

    # Find matching vault project
    local vault_project_dir
    vault_project_dir="$(find_vault_project "$project_name")"

    if [[ -z "$vault_project_dir" ]]; then
        warn "No vault project found for '$project_name' — syncing AGENTS.md only"
    fi

    # Compute the mandatory session-start context
    local session_context
    session_context="$(compute_session_context "$project_name")"

    local content
    content="$(build_agent_content "$project_name" "$vault_project_dir" "$session_context")"

    # Agent instruction files
    write_file "$repo_path/.claude/CLAUDE.md" "$content"
    write_file "$repo_path/.gemini/GEMINI.md" "$content"
    write_file "$repo_path/.github/copilot-instructions.md" "$content"
    write_file "$repo_path/.codex/instructions.md" "$content"

    # Per-agent SessionStart hooks
    write_hook_wrappers "$repo_path" "$project_name"
    write_hook_configs "$repo_path"

    # Ensure generated files are gitignored
    update_gitignore "$repo_path"

    # Clean up old root-level files if they were auto-generated by this script
    for old_file in "$repo_path/CLAUDE.md" "$repo_path/GEMINI.md" "$repo_path/AGENTS.md"; do
        if [[ -f "$old_file" ]] && grep -q "Auto-generated by sync-memory.sh" "$old_file" 2>/dev/null; then
            if $DRY_RUN; then
                echo "  [dry-run] would remove old root-level file: $old_file"
            else
                rm "$old_file"
                ok "Removed old root-level file: $old_file"
            fi
        fi
    done
}

# ── Entry point ───────────────────────────────────────────────────────────────

# Parse flags
args=()
for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=true ;;
        *) args+=("$arg") ;;
    esac
done

if [[ "${#args[@]}" -eq 0 ]]; then
    echo "Usage:"
    echo "  sync-memory.sh <repo-path>              Sync one project"
    echo "  sync-memory.sh --all                    Sync all registered projects"
    echo "  sync-memory.sh <repo-path> --dry-run    Preview without writing"
    exit 1
fi

if [[ "${args[0]}" == "--all" ]]; then
    if [[ ! -f "$PATHS_FILE" ]]; then
        err "No .project-paths file found at $PATHS_FILE"
        echo "  Create it with one absolute project path per line."
        exit 1
    fi
    echo "Syncing all registered projects..."
    while IFS= read -r path; do
        [[ -z "$path" || "$path" == \#* ]] && continue
        sync_project "$path"
    done < "$PATHS_FILE"
    echo ""
    echo "Done."
else
    sync_project "${args[0]}"
    echo ""
    echo "Done."
fi
