#!/usr/bin/env bash
# sync-memory.sh — Sync vault memory to agent-specific files in a project repo.
#
# Usage:
#   sync-memory.sh <repo-path>              Sync one project by repo path
#   sync-memory.sh --all                    Sync all registered projects
#   sync-memory.sh <repo-path> --dry-run    Preview without writing files
#
# The script auto-detects the project name from the repo folder name, finds the
# matching vault project (including nested modules), and generates agent files
# with the right context layering:
#
#   Top-level project → AGENTS.md + project OVERVIEW
#   Module project    → AGENTS.md + module OVERVIEW + parent OVERVIEW

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VAULT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
AGENTS_FILE="$VAULT_DIR/AGENTS.md"
PATHS_FILE="$VAULT_DIR/.project-paths"

DRY_RUN=false

# ── Helpers ──────────────────────────────────────────────────────────────────

log()  { echo "  $*"; }
ok()   { echo "  ✓ $*"; }
warn() { echo "  ⚠ $*" >&2; }
err()  { echo "  ✗ $*" >&2; }

write_file() {
    local path="$1"
    local content="$2"
    if $DRY_RUN; then
        echo "  [dry-run] would write: $path"
    else
        mkdir -p "$(dirname "$path")"
        echo "$content" > "$path"
        ok "$path"
    fi
}

# Find vault project dir for a given project name (searches all nesting levels)
find_vault_project() {
    local name="$1"
    find "$VAULT_DIR/projects" -type d -name "$name" -maxdepth 4 2>/dev/null | head -1
}

# Build the agent file content for a given repo path
build_agent_content() {
    local project_name="$1"
    local vault_project_dir="$2"  # may be empty if no vault project found
    local timestamp
    timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

    local content
    content="$(cat << EOF
# Agent Memory
# Auto-generated by sync-memory.sh — do not edit manually.
# Vault: $VAULT_DIR
# Synced: $timestamp

$(cat "$AGENTS_FILE")
EOF
)"

    if [[ -n "$vault_project_dir" ]]; then
        local parent_dir
        parent_dir="$(dirname "$vault_project_dir")"
        local is_module=false

        # If the parent dir contains an OVERVIEW.md, this is a module
        if [[ "$parent_dir" != "$VAULT_DIR/projects" && -f "$parent_dir/OVERVIEW.md" ]]; then
            is_module=true
        fi

        # Append module OVERVIEW
        if [[ -f "$vault_project_dir/OVERVIEW.md" ]]; then
            content+="

---
# Module Context: $project_name

$(cat "$vault_project_dir/OVERVIEW.md")"
        fi

        # Append parent OVERVIEW if this is a module
        if $is_module && [[ -f "$parent_dir/OVERVIEW.md" ]]; then
            local parent_name
            parent_name="$(basename "$parent_dir")"
            content+="

---
# System Context: $parent_name (parent project)

$(cat "$parent_dir/OVERVIEW.md")"
        fi
    fi

    echo "$content"
}

# Sync one project repo
sync_project() {
    local repo_path="$1"

    if [[ ! -d "$repo_path" ]]; then
        err "Path does not exist: $repo_path"
        return 1
    fi

    local project_name
    project_name="$(basename "$repo_path")"
    echo ""
    echo "→ $project_name  ($repo_path)"

    # Find matching vault project
    local vault_project_dir
    vault_project_dir="$(find_vault_project "$project_name")"

    if [[ -z "$vault_project_dir" ]]; then
        warn "No vault project found for '$project_name' — syncing AGENTS.md only"
    fi

    local content
    content="$(build_agent_content "$project_name" "$vault_project_dir")"

    # Claude Code — .claude/CLAUDE.md
    write_file "$repo_path/.claude/CLAUDE.md" "$content"

    # Gemini CLI — .gemini/GEMINI.md
    write_file "$repo_path/.gemini/GEMINI.md" "$content"

    # GitHub Copilot — .github/copilot-instructions.md
    write_file "$repo_path/.github/copilot-instructions.md" "$content"

    # Codex / OpenAI — .codex/instructions.md
    write_file "$repo_path/.codex/instructions.md" "$content"
}

# ── Entry point ───────────────────────────────────────────────────────────────

# Parse flags
args=()
for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=true ;;
        *) args+=("$arg") ;;
    esac
done

if [[ "${#args[@]}" -eq 0 ]]; then
    echo "Usage:"
    echo "  sync-memory.sh <repo-path>              Sync one project"
    echo "  sync-memory.sh --all                    Sync all registered projects"
    echo "  sync-memory.sh <repo-path> --dry-run    Preview without writing"
    exit 1
fi

if [[ "${args[0]}" == "--all" ]]; then
    if [[ ! -f "$PATHS_FILE" ]]; then
        err "No .project-paths file found at $PATHS_FILE"
        echo "  Create it with one absolute project path per line."
        exit 1
    fi
    echo "Syncing all registered projects..."
    while IFS= read -r path; do
        [[ -z "$path" || "$path" == \#* ]] && continue
        sync_project "$path"
    done < "$PATHS_FILE"
    echo ""
    echo "Done."
else
    sync_project "${args[0]}"
    echo ""
    echo "Done."
fi
